# NMT Workshop Exercise 1: Keras Sequential vs. Functional APIs

In this exercise, we will practice using the two APIs that Keras provides for building deep learning models: the Keras Sequential and Functional APIs.

If you need to reference the syntax of either model, see the Keras documentation pages on the [Sequential](https://keras.io/getting-started/sequential-model-guide/) and [Functional](https://keras.io/getting-started/functional-api-guide/) APIs.

## Part 1: Sequential Voting

For our toy problem, we will use the following data:

In [1]:
import numpy as np
X = np.random.randint(0, 2, size = (1000, 9))
Y = np.where(np.mean(X, axis = 1) > 0.5, 1, 0)

**Questions:**
1. What does it mean that the elements of Y represent a "majority vote" on X?
2. We want to learn how to predict elements of Y from rows of X. Build a Keras Sequential model *model* with one Dense layer (with activation = 'sigmoid') that can be fit on X and Y. Check that the input and output shapes of the model (*model.input_shape* and *model.output_shape*) match the shapes of X and Y.
3. Compile the model with 'mean_squared_error' loss, 'rmsprop' optimizer, and *metrics = ['accuracy']*, and fit it to X and Y with *validation_split = 0.2*. You may choose any values for *epochs* and *batch_size* that result in the model learning well.
4. Once the model has been fit, examine the values of *model.get_weights()*. How do you interpret these values?

1. Y is a vector where 1 occurs if for any line in X, the average of all the values in the vestor is above 0.5, and 0 otherwise. So 1 occurs when there are more 1s than 0s and 0 occurs when there are more 0s than 1s. Therefore it is a majority vote.

In [8]:
from keras.models import Sequential
from keras.layers import Dense, TimeDistributed

In [74]:
x_size = X.shape[1]
model = Sequential()
model.add(Dense(1, activation='sigmoid', input_dim=x_size))
model.compile(loss='mean_squared_error', optimizer='rmsprop', metrics = ['accuracy'])
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_44 (Dense)             (None, 1)                 10        
Total params: 10
Trainable params: 10
Non-trainable params: 0
_________________________________________________________________


In [75]:
model.fit(X, Y, epochs = 100, batch_size=5, validation_split = 0.2)

Train on 800 samples, validate on 200 samples
Epoch 1/100
800/800 [==============================] - 5s 6ms/step - loss: 0.3388 - acc: 0.4350 - val_loss: 0.3148 - val_acc: 0.3750
Epoch 2/100
800/800 [==============================] - 1s 1ms/step - loss: 0.2937 - acc: 0.4300 - val_loss: 0.2695 - val_acc: 0.4450
Epoch 3/100
800/800 [==============================] - 1s 2ms/step - loss: 0.2657 - acc: 0.5113 - val_loss: 0.2469 - val_acc: 0.5800
Epoch 4/100
800/800 [==============================] - 2s 3ms/step - loss: 0.2536 - acc: 0.5663 - val_loss: 0.2375 - val_acc: 0.6050
Epoch 5/100
800/800 [==============================] - 0s 398us/step - loss: 0.2464 - acc: 0.5838 - val_loss: 0.2310 - val_acc: 0.6050
Epoch 6/100
800/800 [==============================] - 1s 1ms/step - loss: 0.2412 - acc: 0.5763 - val_loss: 0.2265 - val_acc: 0.6100
Epoch 7/100
800/800 [==============================] - 2s 3ms/step - loss: 0.2366 - acc: 0.5900 - val_loss: 0.2223 - val_acc: 0.6100
Epoch 8/100
800/800 [

/Users/Yohan/Desktop/anaconda3/lib/python3.7/site-packages/keras/callbacks.py:122: UserWarning: Method on_batch_end() is slow compared to the batch update (0.120115). Check your callbacks.
  % delta_t_median)


800/800 [==============================] - 4s 4ms/step - loss: 0.1756 - acc: 0.8200 - val_loss: 0.1669 - val_acc: 0.8350oss: 0.1776 - acc
Epoch 24/100
800/800 [==============================] - 3s 4ms/step - loss: 0.1726 - acc: 0.8263 - val_loss: 0.1640 - val_acc: 0.8350
Epoch 25/100
800/800 [==============================] - 2s 2ms/step - loss: 0.1697 - acc: 0.8213 - val_loss: 0.1614 - val_acc: 0.8400
Epoch 26/100
800/800 [==============================] - 1s 1ms/step - loss: 0.1671 - acc: 0.8238 - val_loss: 0.1591 - val_acc: 0.8650
Epoch 27/100
800/800 [==============================] - 1s 1ms/step - loss: 0.1644 - acc: 0.8375 - val_loss: 0.1567 - val_acc: 0.8700
Epoch 28/100
800/800 [==============================] - 2s 3ms/step - loss: 0.1620 - acc: 0.8513 - val_loss: 0.1543 - val_acc: 0.8700
Epoch 29/100
800/800 [==============================] - 1s 2ms/step - loss: 0.1595 - acc: 0.8575 - val_loss: 0.1518 - val_acc: 0.8800
Epoch 30/100
800/800 [==============================] - 1s

800/800 [==============================] - 0s 488us/step - loss: 0.0891 - acc: 1.0000 - val_loss: 0.0842 - val_acc: 1.0000
Epoch 84/100
800/800 [==============================] - 0s 594us/step - loss: 0.0885 - acc: 1.0000 - val_loss: 0.0835 - val_acc: 1.0000
Epoch 85/100
800/800 [==============================] - 0s 521us/step - loss: 0.0878 - acc: 1.0000 - val_loss: 0.0827 - val_acc: 1.0000
Epoch 86/100
800/800 [==============================] - 1s 669us/step - loss: 0.0872 - acc: 1.0000 - val_loss: 0.0823 - val_acc: 1.0000
Epoch 87/100
800/800 [==============================] - 0s 568us/step - loss: 0.0865 - acc: 1.0000 - val_loss: 0.0815 - val_acc: 1.0000
Epoch 88/100
800/800 [==============================] - 0s 558us/step - loss: 0.0859 - acc: 1.0000 - val_loss: 0.0810 - val_acc: 1.0000
Epoch 89/100
800/800 [==============================] - 0s 483us/step - loss: 0.0853 - acc: 1.0000 - val_loss: 0.0803 - val_acc: 1.0000
Epoch 90/100
800/800 [==============================] - 0s 53

In [23]:
model.get_weights()

[array([[0.7097542 ],
        [0.6210766 ],
        [0.63398135],
        [0.6162154 ],
        [0.7539241 ],
        [0.6845351 ],
        [0.51169944],
        [0.73884153],
        [0.61793715]], dtype=float32), array([-2.7795007], dtype=float32)]

In [31]:
model.input_shape

(None, 9)

In [32]:
model.output_shape

(None, 1)

The weights are similar for each feature since all features have the same distribution and Y is based on an arithmetic function (arithmetic mean) of the features in X where all the features have the same weight in the mean.

## Part 2: Making it Functional

Now we will practice using Keras's Functional API by rewriting the above model.

**Questions:**

5. Create a model *model2* identical to the above model, but using the Keras Functional API. The model should include an *Input(shape=...)* layer from keras.layers and should use *Model(inputs = ..., outputs = ...)* from keras.models. Fit this model and verify that it produces the same results, and compare the outputs of *model.summary()* and *model2.summary()*.

In [72]:
from keras.layers import Input
from keras.models import Model

# This returns a tensor
inputs = Input(shape=(x_size,))

# a layer instance is callable on a tensor, and returns a tensor
x = Dense(1, activation='sigmoid')(inputs)

# This creates a model that includes
# the Input layer and three Dense layers
model2 = Model(inputs=inputs, outputs=x)
model2.compile(optimizer='rmsprop',
              loss='mean_squared_error',
              metrics=['accuracy'])
model2.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_30 (InputLayer)        (None, 9)                 0         
_________________________________________________________________
dense_43 (Dense)             (None, 1)                 10        
Total params: 10
Trainable params: 10
Non-trainable params: 0
_________________________________________________________________


In [73]:
model2.fit(X, Y, epochs = 70, batch_size=5, validation_split = 0.2)

Train on 800 samples, validate on 200 samples
Epoch 1/70
800/800 [==============================] - 5s 6ms/step - loss: 0.2903 - acc: 0.4563 - val_loss: 0.2760 - val_acc: 0.4450
Epoch 2/70
800/800 [==============================] - 1s 1ms/step - loss: 0.2710 - acc: 0.5063 - val_loss: 0.2565 - val_acc: 0.5450
Epoch 3/70
800/800 [==============================] - 1s 774us/step - loss: 0.2598 - acc: 0.5413 - val_loss: 0.2463 - val_acc: 0.5800
Epoch 4/70
800/800 [==============================] - 1s 1ms/step - loss: 0.2530 - acc: 0.5688 - val_loss: 0.2393 - val_acc: 0.5850
Epoch 5/70
800/800 [==============================] - 0s 553us/step - loss: 0.2471 - acc: 0.5738 - val_loss: 0.2329 - val_acc: 0.6000
Epoch 6/70
800/800 [==============================] - 1s 674us/step - loss: 0.2411 - acc: 0.5788 - val_loss: 0.2270 - val_acc: 0.5950
Epoch 7/70
800/800 [==============================] - ETA: 0s - loss: 0.2352 - acc: 0.596 - 1s 2ms/step - loss: 0.2355 - acc: 0.5963 - val_loss: 0.2218 - va

Epoch 61/70
800/800 [==============================] - 0s 411us/step - loss: 0.1064 - acc: 0.9975 - val_loss: 0.1003 - val_acc: 1.0000
Epoch 62/70
800/800 [==============================] - 0s 491us/step - loss: 0.1054 - acc: 0.9938 - val_loss: 0.0994 - val_acc: 1.0000
Epoch 63/70
800/800 [==============================] - 0s 486us/step - loss: 0.1044 - acc: 0.9975 - val_loss: 0.0985 - val_acc: 1.0000
Epoch 64/70
800/800 [==============================] - 0s 500us/step - loss: 0.1034 - acc: 0.9975 - val_loss: 0.0976 - val_acc: 1.0000
Epoch 65/70
800/800 [==============================] - 0s 613us/step - loss: 0.1025 - acc: 0.9975 - val_loss: 0.0967 - val_acc: 1.0000
Epoch 66/70
800/800 [==============================] - 0s 531us/step - loss: 0.1015 - acc: 0.9975 - val_loss: 0.0957 - val_acc: 1.0000
Epoch 67/70
800/800 [==============================] - 0s 449us/step - loss: 0.1006 - acc: 0.9963 - val_loss: 0.0951 - val_acc: 1.0000
Epoch 68/70
800/800 [==============================] - 

In [30]:
model2.get_weights()

[array([[0.69297874],
        [0.63488173],
        [0.6455374 ],
        [0.60682154],
        [0.7568716 ],
        [0.68070287],
        [0.51847893],
        [0.73426604],
        [0.6264585 ]], dtype=float32), array([-2.7952757], dtype=float32)]

In [35]:
model2.input_shape

(None, 9)

In [33]:
model2.output_shape

(None, 1)

## Part 3: Identifying identical distributions

The previous problem had a nice solution using the Keras Sequential API, but sometimes we will need the Functional API to build more complicated networks. Let's try to learn a slightly more complicated pattern that will be solved more naturally with the Functional API.

Let's generate another dataset:

In [36]:
M1 = np.array([np.random.choice([-10, 10]) for i in range(1000)])
M2 = np.array([np.random.choice([-10, 10]) for i in range(1000)])
S1 = np.stack([
    np.random.normal(m, 1, size = 5)
    for m in M1
])
S2 = np.stack([
    np.random.normal(m, 1, size = 5)
    for m in M2
])
labels = np.where(M1 == M2, 1, 0)

Every row of S1 and S2 is a sample of 5 elements from a distribution with mean either -10 or 10, and the labels in *label* represent whether the given samples are drawn from the same distribution (0: different distributions, 1: same distribution).

We want to train a model to learn how to predict if the two given samples of 5 data points are drawn from the same distribution, i.e. whether they have the same mean.

**Questions:**
6. Create a Functional model using the following architecture:
  * Two Input layers *inp1* and *inp2* (make sure that each has the right *shape=...* parameter)
  * A Dense layer *shared_dense* with output dimension 1 and sigmoid activation function, shared between the input layers. (Define the Dense layer as *shared_dense = Dense(...)* and then set *x1 = shared_dense(inp1)* and *x2 = shared_dense(inp2)*). This means that the same weights will be applied to both inputs.
  * Concatenate the outputs of the dense layers together with *merged = concatenate([x1, x2])*
  * A Dense layer with output dimension 4 and sigmoid activation function, applied to *merged*
  * Another Dense layer with output dimension 1 and sigmoid activation function
  * Finally, define the model as *func_model = Model(inputs = ..., outputs = ...)* for the proper inputs and outputs parameters.
7. Examine the input and output shapes of *func_model* and verify that they match *S1*, *S2*, and *labels*.
8. Compile *func_model* with optimiser *rmsprop*, *binary_crossentropy* loss, and *metrics = ['accuracy']* and fit to *[S1, S2]* and *labels* with *validation_split = 0.2*. Hint: you can use *epochs = 100* and *batch_size = 8* if you are unsure of good values for these hyperparameters. What is the final accuracy that this model achieves?

**Bonus:** Can you interpret the weights in *func_model.get_weights()*?


In [70]:
import keras
# This returns a tensor
s1_size = S1.shape[1]
s2_size = S2.shape[1]
inputs1 = Input(shape=(s1_size,))
inputs2 = Input(shape=(s2_size,))


shared_dense = Dense(1, activation='sigmoid')
x1 = shared_dense(inputs1) 
x2 = shared_dense(inputs2)
merged = keras.layers.concatenate([x1, x2], axis = -1)

dense1 = Dense(4, activation='sigmoid')(merged)
predictions = Dense(1, activation='sigmoid')(dense1)

func_model = Model(inputs=[inputs1, inputs2], outputs = predictions) 
func_model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])
func_model.summary()

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_28 (InputLayer)           (None, 5)            0                                            
__________________________________________________________________________________________________
input_29 (InputLayer)           (None, 5)            0                                            
__________________________________________________________________________________________________
dense_40 (Dense)                (None, 1)            6           input_28[0][0]                   
                                                                 input_29[0][0]                   
__________________________________________________________________________________________________
concatenate_11 (Concatenate)    (None, 2)            0           dense_40[0][0]                   
          

In [71]:
func_model.fit([S1, S2], labels, epochs = 60, batch_size=5, validation_split = 0.2)

Train on 800 samples, validate on 200 samples
Epoch 1/60
800/800 [==============================] - 1s 2ms/step - loss: 0.7212 - acc: 0.4975 - val_loss: 0.7160 - val_acc: 0.4750
Epoch 2/60
800/800 [==============================] - 0s 582us/step - loss: 0.7004 - acc: 0.4975 - val_loss: 0.7037 - val_acc: 0.4750
Epoch 3/60
800/800 [==============================] - 1s 795us/step - loss: 0.6930 - acc: 0.4200 - val_loss: 0.6982 - val_acc: 0.2350
Epoch 4/60
800/800 [==============================] - 0s 542us/step - loss: 0.6901 - acc: 0.2763 - val_loss: 0.6955 - val_acc: 0.2050
Epoch 5/60
800/800 [==============================] - 0s 541us/step - loss: 0.6886 - acc: 0.3163 - val_loss: 0.6939 - val_acc: 0.4850
Epoch 6/60
800/800 [==============================] - 0s 553us/step - loss: 0.6880 - acc: 0.5338 - val_loss: 0.6935 - val_acc: 0.4850
Epoch 7/60
800/800 [==============================] - 1s 683us/step - loss: 0.6872 - acc: 0.6875 - val_loss: 0.6934 - val_acc: 0.4850
Epoch 8/60
800/800

In [60]:
func_model.get_weights()

[array([[ 0.09172858],
        [-0.7042335 ],
        [-0.7649352 ],
        [-0.13719936],
        [-0.5824953 ]], dtype=float32),
 array([0.0379861], dtype=float32),
 array([[-4.749326  , -4.9802036 , -2.562598  ,  0.51760924],
        [-4.9069147 ,  2.6551414 , -2.383913  , -2.4291945 ]],
       dtype=float32),
 array([ 1.0781835 , -1.2654732 , -0.5169826 ,  0.03580838], dtype=float32),
 array([[ 3.6189485],
        [-2.6134408],
        [ 1.2085513],
        [-1.3698591]], dtype=float32),
 array([0.28909597], dtype=float32)]

In [61]:
func_model.input_shape

[(None, 5), (None, 5)]

In [62]:
func_model.output_shape

(None, 1)

In [63]:
S1.shape

(1000, 5)

In [64]:
S2.shape

(1000, 5)

In [65]:
labels.shape

(1000,)

The accuracy reaches 1.000.